import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
// REGISTRY-GETTER-DECODER-INDEX — the browser decoders are pinned to the COMPILER's output, not to a fixture.
//
// web/username-ton-rpc-provider.mjs and web/profile-registry-ton-rpc-provider.mjs read get_global BY POSITION:
// `readStackAddress(stack, 4, ...)`. Add or remove one field in the contract and every later index shifts. A
// stale index does not throw — it returns a different field's value under the right name, so a controller
// address arrives as a treasury address and a count arrives as a manifest hash. Nothing downstream can tell.
//
// The existing provider tests feed those decoders a HAND-WRITTEN stack fixture. That is not independent: the
// fixture and the decoder are edited together, so both can be wrong in the same way and stay green — which is
// exactly what happened while removing the dead Vault binding, and only review caught the third decoder that
// had not been re-indexed.
//
// So this test compares each decoder against build/*/..._{Username,Profile}Registry.ts — generated by the Tact
// compiler straight from the contract, and regenerated by `npm run build`. Two independent producers of the
// same ordering. If a contract field is added, removed, or moved and a decoder is not updated in lockstep,
// this goes red and names the exact position that drifted.
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════

/** Field order the Tact-generated tuple loader reads — the compiler's own view of the getter. */
function generatedFieldOrder(generatedPath: string, loaderName: string): string[] {
  const source = readFileSync(generatedPath, 'utf8');
  const start = source.indexOf(`export function ${loaderName}(source: TupleReader)`);
  expect(start, `${loaderName} must exist in ${generatedPath}`).toBeGreaterThanOrEqual(0);
  const body = source.slice(start, source.indexOf('\n}', start));
  return [...body.matchAll(/const _([A-Za-z0-9_]+) = source\.read[A-Za-z]+\(\)/g)].map((m) => m[1]);
}

/** Field order the hand-written browser decoder reads, paired with the index it actually passes. */
function decoderFieldOrder(modulePath: string, decoderName: string): Array<{ field: string; index: number }> {
  const source = readFileSync(modulePath, 'utf8');
  const start = source.indexOf(`export function ${decoderName}(`);
  expect(start, `${decoderName} must exist in ${modulePath}`).toBeGreaterThanOrEqual(0);
  const body = source.slice(start, source.indexOf('\n}', start));
  return [...body.matchAll(/([A-Za-z0-9_]+): readStack[A-Za-z]+\(stack, (\d+),/g)]
    .map((m) => ({ field: m[1], index: Number(m[2]) }));
}

/** The arity the decoder refuses to read past — its only defence against a shape change. */
function declaredArity(modulePath: string, decoderName: string): number {
  const source = readFileSync(modulePath, 'utf8');
  const body = source.slice(source.indexOf(`export function ${decoderName}(`));
  const match = body.match(/stack\.length !== (\d+)/);
  expect(match, `${decoderName} must guard the stack length`).not.toBeNull();
  return Number(match![1]);
}

const CASES = [
  {
    name: 'UsernameRegistry',
    generated: 'build/UsernameRegistry/UsernameRegistry_UsernameRegistry.ts',
    loader: 'loadTupleUsernameRegistryGlobalView',
    module: 'web/username-ton-rpc-provider.mjs',
    decoder: 'decodeUsernameRegistryGlobalStack',
  },
  {
    name: 'ProfileRegistry',
    generated: 'build/ProfileRegistry/ProfileRegistry_ProfileRegistry.ts',
    loader: 'loadTupleProfileRegistryGlobalView',
    module: 'web/profile-registry-ton-rpc-provider.mjs',
    decoder: 'decodeProfileRegistryGlobalStack',
  },
];

describe('REGISTRY-GETTER-DECODER-INDEX — hand-written decoders track the compiled getter', () => {
  for (const c of CASES) {
    it(`DECODER-IDX-${c.name}: every index maps to the field the compiler puts in that position`, () => {
      const generated = generatedFieldOrder(c.generated, c.loader);
      const decoded = decoderFieldOrder(c.module, c.decoder);

      expect(generated.length, `${c.name} getter must expose fields`).toBeGreaterThan(0);
      // Same fields, same order, and each index equal to its own position — checked field by field so a
      // failure names the exact slot rather than dumping two arrays.
      expect(decoded.map((d) => d.field), `${c.name}: decoder field order vs. compiled getter`).toEqual(generated);
      decoded.forEach((d, position) => {
        expect(d.index, `${c.name}.${d.field} is read from stack[${d.index}] but sits at position ${position}`)
          .toBe(position);
      });
    });

    it(`DECODER-ARITY-${c.name}: the length guard equals the compiled getter's field count`, () => {
      // Without this the guard could be left at the old count, which would reject every live read outright —
      // loud, but only after shipping. Pinning it here catches the omission at build time instead.
      expect(declaredArity(c.module, c.decoder), `${c.name} arity guard`)
        .toBe(generatedFieldOrder(c.generated, c.loader).length);
    });
  }
});
