// Regenerate web/shard-code.mjs from the built shard artifacts.
//
// The browser path cannot import build/*.ts, so the compiled code cells have to reach it as data. Keeping that
// data GENERATED rather than pasted is the whole point: a shard's address is hash(StateInit{code, data}), so a
// stale code cell yields a wrong address — and a message to a wrong (therefore uninitialised) address succeeds
// with its compute phase skipped. The wallet reports success and the message is simply gone. tests/
// shard-browser-address.test.ts runs this and fails if the checked-in file differs.
import { readFileSync, writeFileSync } from 'node:fs';

// KeyShard is here for the same reason as the other three even though it is not epoch-keyed: its address is
// hash(code, data) over a code cell the browser cannot import, and both the identity read and the avatar read
// now resolve through it. PublicShard (added 2026-07-21) is the public/avatar lane; the client derives channel,
// thread, beacon and avatar shard addresses from its code hash to sweep the directory and render the feed.
const SHARDS = ['RecordShard', 'IntroShard', 'RecoveryShard', 'KeyShard', 'PublicShard'];

export function renderShardCodeModule() {
  const lines = [
    '// shard-code — the compiled shard code cells, as base64 BOC, for the BROWSER path.',
    '//',
    '// GENERATED by scripts/generate_shard_code.mjs from build/. Do not hand-edit: tests/shard-browser-address.test.ts',
    '// regenerates it and fails if this file has drifted, because a stale code cell here produces a WRONG shard address',
    '// and — under lazy deploy, where a message to an uninitialised account succeeds with its compute phase skipped —',
    '// a wrong address is a message that vanishes with the wallet reporting success.',
    '',
  ];
  for (const name of SHARDS) {
    const boc = readFileSync(`build/${name}/${name}_${name}.code.boc`).toString('base64');
    lines.push(`export const ${name.toUpperCase()}_CODE_BOC = '${boc}';`);
    lines.push('');
  }
  return lines.join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('generate_shard_code.mjs')) {
  writeFileSync('web/shard-code.mjs', renderShardCodeModule());
  console.log('web/shard-code.mjs regenerated');
}
